# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [master]
  pull_request:
    branches: '*'

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x, 12.x, 14.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm ci
      - run: npm run build
        env:
          CI: true
      - uses: actions/upload-artifact@v2
        with:
          name: firebase-tools-ui
          path: |
            build/
            server.bundle.js

  unit:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x, 12.x, 14.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm ci
      - name: Run tests against emulator
        run: |
          npm install -g firebase-tools
          firebase emulators:exec --only database,firestore --project sample 'npm run test:coverage -- --forceExit'
        env:
          CI: true

  e2e:
    runs-on: ubuntu-latest

    needs: build

    strategy:
      matrix:
        node-version: [14.x]

    steps:
      - uses: actions/checkout@v2
      - uses: actions/download-artifact@v2
        with:
          name: firebase-tools-ui
      - name: Display structure of downloaded files
        run: ls -R
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm i -g firebase-tools
      # - name: Display structure of node-bins
      #   run: ls ./node_modules/.bin
      - name: Create firebase.json
        uses: jsdaniell/create-json@1.1.2
        with:
          name: "firebase.json"
          json: '{"emulators":{"auth":{"port":9099},"functions":{"port":5001},"firestore":{"port":8080},"database":{"port":9000},"hosting":{"port":5000},"pubsub":{"port":8085}}}'
      - run: pwd
      - run: ls
      - name: Run cypress specs
        uses: cypress-io/github-action@v2
        with:
          start: firebase emulators:exec --project sample --import test-data 'PORT=3000 npm run start:prod'
          wait-on: 'http://localhost:3000'

  check-package-lock:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm install --package-lock-only
      - run: "git diff --exit-code -- package-lock.json || (echo 'Error: package-lock.json is changed during npm install! Please make sure to use npm >= 6.9.0 and commit package-lock.json.' && false)"
